spring:
  datasource:

    url: jdbc:mysql://localhost:3306/meeting-planner?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081




#springdoc:
#  swagger-ui:
#    enabled=true:








#server:
#  port: 8080
#
#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/meeting-planner
#    username: root
#    password:
#  application:
#    name: Meeting-Planner